//! Entity data synchronization system.
//!
//! This module provides the infrastructure for syncing entity state (health, pose, flags, etc.)
//! between server and client via the `SetEntityData` packet.
//!
//! # Architecture
//!
//! - [`SyncedValue<T>`] - Wrapper that tracks per-field dirty state
//! - [`EntityData`] - Type-erased enum for network serialization
//! - [`DataValue`] - Network-ready value with index and serializer info
//! - [`EntityPose`] - Entity pose states (standing, sneaking, swimming, etc.)
//! - [`EntityDataSerializerRegistry`] - Registry of serializers with writers
//!
//! # Serialization Flow
//!
//! Serialization happens through the registry, not directly on `EntityData`:
//! ```ignore
//! let writer = REGISTRY.entity_data_serializers.get_writer(serializer_id).unwrap();
//! writer(&entity_data_value, &mut buf)?;
//! ```
//!
//! # Generated Code
//!
//! Per-entity data structs (e.g., `PlayerEntityData`) are generated by the build script
//! from `entities.json` and live in `steel-registry/src/generated/entity_data.rs`.

mod serializer;
mod vanilla_serializers;

pub use serializer::{
    EntityDataSerializerEntry, EntityDataSerializerEntryRef, EntityDataSerializerRegistry,
    EntityDataWriter,
};
pub use vanilla_serializers::register_vanilla_entity_data_serializers;

use std::{
    io,
    str::FromStr,
    sync::atomic::{AtomicU32, Ordering},
};

use steel_utils::{
    BlockStateId, Identifier,
    codec::VarInt,
    serial::{ReadFrom, WriteTo},
};
use text_components::TextComponent;
use uuid::Uuid;

use crate::item_stack::ItemStack;

// Re-export types used in generated code
pub use crate::blocks::properties::Direction;
pub use steel_utils::BlockPos;

/// Wrapper that holds a synced value alongside its default.
///
/// Each field in an entity data struct is wrapped in `SyncedValue`. Dirty tracking
/// lives in the owning layer's [`DirtyBits`] bitfield, not here, so that a whole
/// layer needs only a single atomic instead of one flag per field.
#[derive(Debug, Clone)]
pub struct SyncedValue<T> {
    value: T,
    default: T,
}

impl<T: Clone + PartialEq> SyncedValue<T> {
    /// Create a new synced value with the given default.
    pub fn new(default: T) -> Self {
        Self {
            value: default.clone(),
            default,
        }
    }

    /// Get a reference to the current value.
    #[inline]
    pub fn get(&self) -> &T {
        &self.value
    }

    /// Set the value, returning `true` if it actually changed.
    ///
    /// The caller (a generated `set_<field>` method) is responsible for marking the
    /// corresponding bit in the layer's [`DirtyBits`] when this returns `true`.
    #[inline]
    pub fn set(&mut self, value: T) -> bool {
        if self.value != value {
            self.value = value;
            true
        } else {
            false
        }
    }

    /// Returns true if the current value equals the default.
    #[inline]
    pub fn is_default(&self) -> bool {
        self.value == self.default
    }
}

/// Per-layer dirty bitfield.
///
/// Each generated entity-data layer owns a single `DirtyBits`. A field's dirty state
/// is stored at a fixed bit position (its ordinal within the layer), assigned by the
/// build script. Being atomic lets `pack_dirty`/`is_dirty` run behind `&self`.
#[derive(Debug, Default)]
pub struct DirtyBits(AtomicU32);

impl DirtyBits {
    /// Create an empty (all-clean) bitfield.
    #[inline]
    pub const fn new() -> Self {
        Self(AtomicU32::new(0))
    }

    /// Mark the field at `bit` as dirty.
    #[inline]
    pub fn mark(&self, bit: u32) {
        self.0.fetch_or(1 << bit, Ordering::Relaxed);
    }

    /// Snapshot the current dirty bits and clear them in one atomic operation.
    #[inline]
    pub fn take(&self) -> u32 {
        self.0.swap(0, Ordering::Relaxed)
    }

    /// Returns true if any field is dirty.
    #[inline]
    pub fn any(&self) -> bool {
        self.0.load(Ordering::Relaxed) != 0
    }
}

impl Clone for DirtyBits {
    fn clone(&self) -> Self {
        Self(AtomicU32::new(self.0.load(Ordering::Relaxed)))
    }
}

/// Entity pose states.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[repr(u8)]
pub enum EntityPose {
    #[default]
    Standing = 0,
    FallFlying = 1,
    Sleeping = 2,
    Swimming = 3,
    SpinAttack = 4,
    Sneaking = 5,
    LongJumping = 6,
    Dying = 7,
    Croaking = 8,
    UsingTongue = 9,
    Sitting = 10,
    Roaring = 11,
    Sniffing = 12,
    Emerging = 13,
    Digging = 14,
    Sliding = 15,
    Shooting = 16,
    Inhaling = 17,
}

impl FromStr for EntityPose {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "STANDING" => Ok(Self::Standing),
            "FALL_FLYING" => Ok(Self::FallFlying),
            "SLEEPING" => Ok(Self::Sleeping),
            "SWIMMING" => Ok(Self::Swimming),
            "SPIN_ATTACK" => Ok(Self::SpinAttack),
            "SNEAKING" | "CROUCHING" => Ok(Self::Sneaking),
            "LONG_JUMPING" => Ok(Self::LongJumping),
            "DYING" => Ok(Self::Dying),
            "CROAKING" => Ok(Self::Croaking),
            "USING_TONGUE" => Ok(Self::UsingTongue),
            "SITTING" => Ok(Self::Sitting),
            "ROARING" => Ok(Self::Roaring),
            "SNIFFING" => Ok(Self::Sniffing),
            "EMERGING" => Ok(Self::Emerging),
            "DIGGING" => Ok(Self::Digging),
            "SLIDING" => Ok(Self::Sliding),
            "SHOOTING" => Ok(Self::Shooting),
            "INHALING" => Ok(Self::Inhaling),
            _ => Err(()),
        }
    }
}

/// Rotations for armor stands and similar entities (pitch, yaw, roll in degrees).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Rotations {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl Rotations {
    pub const ZERO: Self = Self {
        x: 0.0,
        y: 0.0,
        z: 0.0,
    };

    pub fn new(x: f32, y: f32, z: f32) -> Self {
        Self { x, y, z }
    }
}

/// Main hand preference (left or right).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[repr(u8)]
pub enum HumanoidArm {
    Left = 0,
    #[default]
    Right = 1,
}

impl ReadFrom for HumanoidArm {
    fn read(data: &mut std::io::Cursor<&[u8]>) -> io::Result<Self> {
        match VarInt::read(data)?.0 {
            0 => Ok(Self::Left),
            1 => Ok(Self::Right),
            value => Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("invalid humanoid arm id {value}"),
            )),
        }
    }
}

/// Villager profession, type, and level data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct VillagerData {
    /// Villager type (biome variant) - registry ID.
    pub villager_type: i32,
    /// Profession - registry ID.
    pub profession: i32,
    /// Trading level (1-5).
    pub level: i32,
}

impl VillagerData {
    pub fn new(villager_type: i32, profession: i32, level: i32) -> Self {
        Self {
            villager_type,
            profession,
            level,
        }
    }
}

/// A global position (dimension + block position).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GlobalPos {
    pub dimension: Identifier,
    pub pos: BlockPos,
}

impl GlobalPos {
    pub fn new(dimension: Identifier, pos: BlockPos) -> Self {
        Self { dimension, pos }
    }
}

/// A 3D vector (for display entities).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Vector3f {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl Vector3f {
    pub const ZERO: Self = Self {
        x: 0.0,
        y: 0.0,
        z: 0.0,
    };

    pub fn new(x: f32, y: f32, z: f32) -> Self {
        Self { x, y, z }
    }
}

/// A quaternion rotation (for display entities).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Quaternionf {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}

impl Quaternionf {
    pub const IDENTITY: Self = Self {
        x: 0.0,
        y: 0.0,
        z: 0.0,
        w: 1.0,
    };

    pub fn new(x: f32, y: f32, z: f32, w: f32) -> Self {
        Self { x, y, z, w }
    }
}

/// Particle-specific payload written after the particle type id.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParticleOptions {
    None,
    Color { color: i32 },
}

/// Particle effect data.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParticleData {
    /// Particle type registry ID.
    pub particle_type: i32,
    pub options: ParticleOptions,
}

impl ParticleData {
    #[must_use]
    pub fn new(particle_type: i32, options: ParticleOptions) -> Self {
        Self {
            particle_type,
            options,
        }
    }
}

/// A list of particle effects.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ParticleList {
    pub particles: Vec<ParticleData>,
}

/// Game profile for player heads and similar.
// TODO: Implement proper profile with UUID, name, and properties
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ResolvableProfile {
    // TODO: Add fields when needed
}

/// Sniffer entity state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[repr(u8)]
pub enum SnifferState {
    #[default]
    Idling = 0,
    FeelingHappy = 1,
    Scenting = 2,
    Sniffing = 3,
    Searching = 4,
    Digging = 5,
    Rising = 6,
}

/// Armadillo entity state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[repr(u8)]
pub enum ArmadilloState {
    #[default]
    Idle = 0,
    RollingUp = 1,
    Rolled = 2,
    Unrolling = 3,
    Scared = 4,
}

/// Type-erased entity data for network encoding.
///
/// This enum holds the actual value to be sent over the network.
/// Serialization happens through the [`EntityDataSerializerRegistry`], not directly
/// on this type. Use `REGISTRY.entity_data_serializers.get_writer(id)` to get the
/// writer function for a specific serializer ID.
#[derive(Debug, Clone)]
pub enum EntityData {
    // Primitive types
    Byte(i8),
    Int(i32),
    Long(i64),
    Float(f32),
    String(String),
    Boolean(bool),

    // Text components
    Component(Box<TextComponent>),
    OptionalComponent(Option<Box<TextComponent>>),

    // Item
    ItemStack(ItemStack),

    // Spatial types
    Rotations(Rotations),
    BlockPos(BlockPos),
    OptionalBlockPos(Option<BlockPos>),
    Direction(Direction),
    OptionalLivingEntityRef(Option<Uuid>),
    BlockState(BlockStateId),
    OptionalBlockState(Option<BlockStateId>),
    Vector3(Vector3f),
    Quaternion(Quaternionf),

    // Entity states
    Pose(EntityPose),
    SnifferState(SnifferState),
    ArmadilloState(ArmadilloState),

    // Particles
    Particle(ParticleData),
    Particles(ParticleList),

    // Villager
    VillagerData(VillagerData),

    // Optional numeric
    OptionalUnsignedInt(Option<u32>),

    // Holder/registry reference variants (VarInt registry IDs)
    CatVariant(i32),
    CatSoundVariant(i32),
    CowVariant(i32),
    CowSoundVariant(i32),
    WolfVariant(i32),
    WolfSoundVariant(i32),
    FrogVariant(i32),
    PigVariant(i32),
    PigSoundVariant(i32),
    ChickenVariant(i32),
    ChickenSoundVariant(i32),
    ZombieNautilusVariant(i32),
    PaintingVariant(i32),

    // Global position
    OptionalGlobalPos(Option<GlobalPos>),

    // Copper golem / weathering states (future entities)
    CopperGolemState(i32),
    WeatheringCopperState(i32),

    // Profile
    ResolvableProfile(ResolvableProfile),

    // Player
    HumanoidArm(HumanoidArm),
}

/// Network-ready data value with index and serializer info.
///
/// This is what gets written to the `SetEntityData` packet.
#[derive(Debug, Clone)]
pub struct DataValue {
    /// The index of this data field (0-254, 255 is terminator).
    pub index: u8,
    /// The serializer ID (from registration order in EntityDataSerializerRegistry).
    pub serializer_id: i32,
    /// The actual value to write.
    pub value: EntityData,
}

impl DataValue {
    /// Write this data value to the buffer (without terminator).
    ///
    /// Uses the global registry to look up the writer function for this serializer.
    pub fn write_to(&self, buf: &mut Vec<u8>) -> io::Result<()> {
        use crate::REGISTRY;

        self.index.write(buf)?;
        VarInt(self.serializer_id).write(buf)?;

        let writer = REGISTRY
            .entity_data_serializers
            .get_writer(self.serializer_id)
            .ok_or_else(|| {
                io::Error::other(format!(
                    "Unknown entity data serializer ID: {}",
                    self.serializer_id
                ))
            })?;

        writer(&self.value, buf)
    }
}

/// Write a list of data values to a buffer, with the 0xFF terminator.
pub fn write_data_values(values: &[DataValue], buf: &mut Vec<u8>) -> io::Result<()> {
    for value in values {
        value.write_to(buf)?;
    }
    // Write terminator
    0xFFu8.write(buf)
}

#[cfg(test)]
mod tests {
    use steel_utils::{Identifier, codec::VarInt, serial::WriteTo};

    use crate::vanilla_entity_data::{EggEntityData, ItemEntityData};
    use crate::{Registry, RegistryExt};

    use super::{
        EntityData, EntityDataSerializerRegistry, ParticleData, ParticleOptions,
        register_vanilla_entity_data_serializers,
    };

    #[test]
    fn projectile_item_stack_defaults_use_extracted_item() {
        let data = EggEntityData::new();
        let stack = data.throwable_item_projectile().item_stack.get();

        assert_eq!(&stack.item().key, &Identifier::vanilla_static("egg"));
        assert_eq!(stack.count(), 1);
        assert!(data.pack_all().is_empty());
    }

    #[test]
    fn empty_item_stack_defaults_remain_empty() {
        let data = ItemEntityData::new();

        assert!(data.item.get().is_empty());
        assert!(data.pack_all().is_empty());
    }

    #[test]
    fn entity_effect_particle_color_options_encode_payload() {
        let registry = Registry::new_vanilla();
        let entity_effect = Identifier::vanilla_static("entity_effect");
        let Some(particle_type_id) = registry.particle_types.id_from_key(&entity_effect) else {
            panic!("entity_effect particle type must be registered");
        };

        let mut serializers = EntityDataSerializerRegistry::new();
        register_vanilla_entity_data_serializers(&mut serializers);

        let Some(serializer_id) = serializers.id_from_key(&Identifier::vanilla_static("particle"))
        else {
            panic!("particle entity-data serializer must be registered");
        };

        let Some(writer) = serializers.get_writer(serializer_id as i32) else {
            panic!("particle entity-data serializer must have a writer");
        };

        let particle = ParticleData::new(
            particle_type_id as i32,
            ParticleOptions::Color { color: -1 },
        );
        let value = EntityData::Particle(particle);
        let mut encoded = Vec::new();
        let result = writer(&value, &mut encoded);
        assert!(result.is_ok(), "{result:?}");

        let mut expected = Vec::new();
        let result = VarInt(particle_type_id as i32).write(&mut expected);
        assert!(result.is_ok(), "{result:?}");
        let result = (-1i32).write(&mut expected);
        assert!(result.is_ok(), "{result:?}");

        assert_eq!(encoded, expected);
    }
}
